### PR TITLE
Code status issue

### PR DESCRIPTION
**Pull request by michelre**
I encountered an issue with the code status inside the callback. It seems like this code status was always set to 0 even when the process failed due to an error!

### CODE REVIEW

**Comment by uschmann** [comment]
For what was the '| cat' used anyway?

**Comment by timstudd** [comment]
@michelre - Not sure how I missed your PR and sorry for the delay.  Happy to merge the change.  Can you also bump the version number?

**Comment by michelre** [comment]
@timstudd thanks for the merge. Do I really need to increase the version number? Cause, it seems like you've already done it! ;)

**Comment by timstudd** [comment]
@michelre Sure thing.  As your request was put in so long ago, after my last comment, I felt bad asking you to bump the version so I went ahead and did it in a separate PR. Thanks again for the contribution!

**Pull request merged**
